

server:
    port: 8080
    servlet:
        context-path: /api
spring:
    profiles:
        active: dev
    datasource:
        url: jdbc:mysql://103.173.227.90:3306/tour-booking
        username: tour-booking
        password: n0XKVVma)hmE
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    mail:
        host: "smtp.gmail.com"
        port: 587
        username: "duckg2083@gmail.com"
        password: "ofjs suun slcd kfkm"
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
jwt:
    secret: "4k/ODvsqmoCjC4kWDJHLab6+9Xu4V2G6wIH+T0C17zBuJtxeSjQDnCI7fi3ZMdCT"
