server:
    port: 8080
    servlet:
        context-path: /api
spring:
    # datasource:
    #     url: jdbc:mysql://localhost:3308/springbootdb
    #     username: root
    #     password: root
    #     driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
